services:
  archivedex.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__PostgreSQL=Host=postgres;Database=archivedex;Username=archivedex;Password=archivedex;Trust Server Certificate=true;SslMode=Prefer
    ports:
      - "8080"

  postgres:
    ports:
      - "5432:5432"

  pgadmin:
    ports:
      - "5050:80"
