// <auto-generated />
using System;
using ArchiveDex.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ArchiveDex.Infrastructure.Migrations
{
    [DbContext(typeof(ArchiveDexDbContext))]
    [Migration("20260618150626_AddImportJobMergedCount")]
    partial class AddImportJobMergedCount
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArchiveDex.Domain.Entities.Administrator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<int>("PreferredUiCulture")
                        .HasColumnType("integer");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ArchiveDex.Domain.Entities.ApplicationConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CollectionCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("DatabaseConnectionString")
                        .HasColumnType("text");

                    b.Property<string>("DatabaseMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DefaultUiCulture")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageStoragePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImportSettings")
                        .HasColumnType("text");

                    b.Property<bool>("IsSetupComplete")
                        .HasColumnType("boolean");

                    b.Property<string>("OcrSettings")
                        .HasColumnType("text");

                    b.Property<string>("ScannerDefaults")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ApplicationConfigurations");
                });

            modelBuilder.Entity("ArchiveDex.Domain.Entities.CardExternalId", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CardPrintId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CardPrintId");

                    b.HasIndex("Source", "ExternalId", "Language")
                        .IsUnique();

                    b.ToTable("CardExternalIds");
                });

            modelBuilder.Entity("ArchiveDex.Domain.Entities.CardPrint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AttacksJson")
                        .HasColumnType("text");

                    b.Property<string>("CardLanguage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CardSetId")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DexIdsJson")
                        .HasColumnType("text");

                    b.Property<string>("EvolveFrom")
                        .HasColumnType("text");

                    b.Property<int?>("Hp")
                        .HasColumnType("integer");

                    b.Property<string>("Illustrator")
                        .HasColumnType("text");

                    b.Property<string>("ImagePath")
                        .HasColumnType("text");

                    b.Property<bool?>("LegalExpanded")
                        .HasColumnType("boolean");

                    b.Property<bool?>("LegalStandard")
                        .HasColumnType("boolean");

                    b.Property<string>("Level")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rarity")
                        .HasColumnType("text");

                    b.Property<string>("RegulationMark")
                        .HasColumnType("text");

                    b.Property<string>("ResistancesJson")
                        .HasColumnType("text");

                    b.Property<int?>("Retreat")
                        .HasColumnType("integer");

                    b.Property<string>("Stage")
                        .HasColumnType("text");

                    b.Property<string>("Suffix")
                        .HasColumnType("text");

                    b.Property<string>("TypesJson")
                        .HasColumnType("text");

                    b.Property<bool>("VariantFirstEdition")
                        .HasColumnType("boolean");

                    b.Property<bool>("VariantHolo")
                        .HasColumnType("boolean");

                    b.Property<bool>("VariantNormal")
                        .HasColumnType("boolean");

                    b.Property<bool>("VariantReverse")
                        .HasColumnType("boolean");

                    b.Property<string>("WeaknessesJson")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CardSetId");

                    b.HasIndex("Name");

                    b.HasIndex("CardLanguage", "Number");

                    b.ToTable("CardPrints");
                });

            modelBuilder.Entity("ArchiveDex.Domain.Entities.CardSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CanonicalName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("OfficialTotal")
                        .HasColumnType("integer");

                    b.Property<int?>("PrintedTotal")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<string>("Series")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalName");

                    b.HasIndex("ReleaseDate");

                    b.ToTable("CardSets");
                });

            modelBuilder.Entity("ArchiveDex.Domain.Entities.CardSetExternalId", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CardSetId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExternalName")
                        .HasColumnType("text");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SourceOfficialTotal")
                        .HasColumnType("integer");

                    b.Property<int?>("SourcePrintedTotal")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("SourceReleaseDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CardSetId");

                    b.HasIndex("Source", "Language", "ExternalId")
                        .IsUnique();

                    b.ToTable("CardSetExternalIds");
                });

            modelBuilder.Entity("ArchiveDex.Domain.Entities.CollectionEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CardPrintId")
                        .HasColumnType("uuid");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FrontImagePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<decimal?>("PurchasePrice")
                        .HasColumnType("numeric");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("StorageLocation")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CardPrintId");

                    b.ToTable("CollectionEntries");
                });

            modelBuilder.Entity("ArchiveDex.Domain.Entities.ImageAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("ImageAssets");
                });

            modelBuilder.Entity("ArchiveDex.Domain.Entities.ImportJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Errors")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ImportedCount")
                        .HasColumnType("integer");

                    b.Property<int>("MergedCount")
                        .HasColumnType("integer");

                    b.Property<string>("SelectedCardLanguages")
                        .HasColumnType("text");

                    b.Property<string>("SelectedSets")
                        .HasColumnType("text");

                    b.Property<int>("SkippedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UpdatedCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ImportJobs");
                });

            modelBuilder.Entity("ArchiveDex.Domain.Entities.LocalCorrection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CardPrintId")
                        .HasColumnType("uuid");

                    b.Property<string>("NameOverride")
                        .HasColumnType("text");

                    b.Property<string>("NumberOverride")
                        .HasColumnType("text");

                    b.Property<string>("OtherOverrides")
                        .HasColumnType("text");

                    b.Property<Guid?>("SetOverride")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CardPrintId")
                        .IsUnique();

                    b.ToTable("LocalCorrections");
                });

            modelBuilder.Entity("ArchiveDex.Domain.Entities.OcrResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CandidateMatches")
                        .HasColumnType("text");

                    b.Property<float?>("Confidence")
                        .HasColumnType("real");

                    b.Property<string>("DetectedCardLanguage")
                        .HasColumnType("text");

                    b.Property<string>("DetectedName")
                        .HasColumnType("text");

                    b.Property<string>("DetectedNumber")
                        .HasColumnType("text");

                    b.Property<string>("DetectedSetHint")
                        .HasColumnType("text");

                    b.Property<string>("RawText")
                        .HasColumnType("text");

                    b.Property<Guid>("ScanJobId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ScanJobId")
                        .IsUnique();

                    b.ToTable("OcrResults");
                });

            modelBuilder.Entity("ArchiveDex.Domain.Entities.PendingSetMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IncomingExternalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IncomingLanguage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IncomingName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("IncomingOfficialTotal")
                        .HasColumnType("integer");

                    b.Property<int?>("IncomingPrintedTotal")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("IncomingReleaseDate")
                        .HasColumnType("date");

                    b.Property<string>("IncomingSource")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReasonsJson")
                        .HasColumnType("text");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SuggestedCardSetId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("SuggestedCardSetId");

                    b.HasIndex("IncomingSource", "IncomingLanguage", "IncomingExternalId");

                    b.ToTable("PendingSetMappings");
                });

            modelBuilder.Entity("ArchiveDex.Domain.Entities.ScanJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ImageAssetId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OcrResultId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ResultingCollectionEntryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ImageAssetId");

                    b.ToTable("ScanJobs");
                });

            modelBuilder.Entity("ArchiveDex.Domain.Entities.SetMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CardSetId")
                        .HasColumnType("uuid");

                    b.Property<string>("Confidence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsManual")
                        .HasColumnType("boolean");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CardSetId");

                    b.HasIndex("Source", "Language", "ExternalId")
                        .IsUnique();

                    b.ToTable("SetMappings");
                });

            modelBuilder.Entity("ArchiveDex.Domain.Entities.SetRelation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Confidence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsManual")
                        .HasColumnType("boolean");

                    b.Property<string>("RelationType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SourceSetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetSetId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TargetSetId");

                    b.HasIndex("SourceSetId", "TargetSetId", "RelationType")
                        .IsUnique();

                    b.ToTable("SetRelations");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ArchiveDex.Domain.Entities.CardExternalId", b =>
                {
                    b.HasOne("ArchiveDex.Domain.Entities.CardPrint", "CardPrint")
                        .WithMany("ExternalIds")
                        .HasForeignKey("CardPrintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CardPrint");
                });

            modelBuilder.Entity("ArchiveDex.Domain.Entities.CardPrint", b =>
                {
                    b.HasOne("ArchiveDex.Domain.Entities.CardSet", "CardSet")
                        .WithMany("Cards")
                        .HasForeignKey("CardSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CardSet");
                });

            modelBuilder.Entity("ArchiveDex.Domain.Entities.CardSetExternalId", b =>
                {
                    b.HasOne("ArchiveDex.Domain.Entities.CardSet", "CardSet")
                        .WithMany("ExternalIds")
                        .HasForeignKey("CardSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CardSet");
                });

            modelBuilder.Entity("ArchiveDex.Domain.Entities.CollectionEntry", b =>
                {
                    b.HasOne("ArchiveDex.Domain.Entities.CardPrint", "CardPrint")
                        .WithMany("CollectionEntries")
                        .HasForeignKey("CardPrintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CardPrint");
                });

            modelBuilder.Entity("ArchiveDex.Domain.Entities.LocalCorrection", b =>
                {
                    b.HasOne("ArchiveDex.Domain.Entities.CardPrint", "CardPrint")
                        .WithOne("LocalCorrection")
                        .HasForeignKey("ArchiveDex.Domain.Entities.LocalCorrection", "CardPrintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CardPrint");
                });

            modelBuilder.Entity("ArchiveDex.Domain.Entities.OcrResult", b =>
                {
                    b.HasOne("ArchiveDex.Domain.Entities.ScanJob", "ScanJob")
                        .WithOne("OcrResult")
                        .HasForeignKey("ArchiveDex.Domain.Entities.OcrResult", "ScanJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScanJob");
                });

            modelBuilder.Entity("ArchiveDex.Domain.Entities.PendingSetMapping", b =>
                {
                    b.HasOne("ArchiveDex.Domain.Entities.CardSet", "SuggestedCardSet")
                        .WithMany()
                        .HasForeignKey("SuggestedCardSetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SuggestedCardSet");
                });

            modelBuilder.Entity("ArchiveDex.Domain.Entities.ScanJob", b =>
                {
                    b.HasOne("ArchiveDex.Domain.Entities.ImageAsset", "ImageAsset")
                        .WithMany()
                        .HasForeignKey("ImageAssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImageAsset");
                });

            modelBuilder.Entity("ArchiveDex.Domain.Entities.SetMapping", b =>
                {
                    b.HasOne("ArchiveDex.Domain.Entities.CardSet", "CardSet")
                        .WithMany()
                        .HasForeignKey("CardSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CardSet");
                });

            modelBuilder.Entity("ArchiveDex.Domain.Entities.SetRelation", b =>
                {
                    b.HasOne("ArchiveDex.Domain.Entities.CardSet", "SourceSet")
                        .WithMany()
                        .HasForeignKey("SourceSetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArchiveDex.Domain.Entities.CardSet", "TargetSet")
                        .WithMany()
                        .HasForeignKey("TargetSetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourceSet");

                    b.Navigation("TargetSet");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("ArchiveDex.Domain.Entities.Administrator", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("ArchiveDex.Domain.Entities.Administrator", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArchiveDex.Domain.Entities.Administrator", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("ArchiveDex.Domain.Entities.Administrator", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ArchiveDex.Domain.Entities.CardPrint", b =>
                {
                    b.Navigation("CollectionEntries");

                    b.Navigation("ExternalIds");

                    b.Navigation("LocalCorrection");
                });

            modelBuilder.Entity("ArchiveDex.Domain.Entities.CardSet", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("ExternalIds");
                });

            modelBuilder.Entity("ArchiveDex.Domain.Entities.ScanJob", b =>
                {
                    b.Navigation("OcrResult");
                });
#pragma warning restore 612, 618
        }
    }
}
