// <auto-generated />
using System;
using ArchiveDex.Server.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ArchiveDex.Server.Migrations
{
    [DbContext(typeof(ArchiveDexDbContext))]
    [Migration("20260728082304_AddCardCropVariant")]
    partial class AddCardCropVariant
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArchiveDex.Server.Infrastructure.Persistence.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ArchiveDex.Server.Infrastructure.Persistence.CaptureBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "ExpiresAt");

                    b.ToTable("CaptureBatches");
                });

            modelBuilder.Entity("ArchiveDex.Server.Infrastructure.Persistence.CaptureDraft", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnalysisProposal")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("BatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("CandidateReferences")
                        .HasColumnType("jsonb");

                    b.Property<string>("ConfirmedFields")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorCode")
                        .HasColumnType("text");

                    b.Property<string>("ErrorDetail")
                        .HasColumnType("text");

                    b.Property<bool>("ErrorRetryable")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ImageAssetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ProcessingStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProviderCorrelationId")
                        .HasColumnType("text");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("ImageAssetId")
                        .IsUnique();

                    b.HasIndex("OwnerId", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("Status", "UpdatedAt")
                        .HasFilter("\"ProviderCorrelationId\" IS NOT NULL");

                    b.HasIndex("OwnerId", "BatchId", "Status");

                    b.HasIndex("OwnerId", "Status", "ExpiresAt");

                    b.ToTable("CaptureDrafts", t =>
                        {
                            t.HasCheckConstraint("CK_CaptureDraft_RetryCount", "\"RetryCount\" >= 0 AND \"RetryCount\" <= 3");

                            t.HasCheckConstraint("CK_CaptureDraft_Status", "\"Status\" IN ('uploaded', 'analyzing', 'needsReview', 'needsNewImage', 'failed')");
                        });
                });

            modelBuilder.Entity("ArchiveDex.Server.Infrastructure.Persistence.CardRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CardmarketMatchState")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CardmarketMatchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CardmarketProductId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CatalogCardReferenceId")
                        .HasColumnType("uuid");

                    b.Property<string>("CollectorNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GermanName")
                        .HasColumnType("text");

                    b.Property<string>("GermanNameUnavailableReason")
                        .HasColumnType("text");

                    b.Property<string>("NumberNormalized")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumberSortKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("PrintedNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SetEditionId")
                        .HasColumnType("uuid");

                    b.Property<string>("SetTotal")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VariantKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CatalogCardReferenceId");

                    b.HasIndex("SetEditionId");

                    b.HasIndex("OwnerId", "SetEditionId", "NumberNormalized", "VariantKey")
                        .IsUnique();

                    b.HasIndex("OwnerId", "SetEditionId", "NumberSortKey", "Id");

                    b.ToTable("CardRecords", t =>
                        {
                            t.HasCheckConstraint("CK_CardRecord_CardmarketMatchState", "\"CardmarketMatchState\" IS NULL OR \"CardmarketMatchState\" IN ('unique', 'narrowSpread', 'aiResolved', 'manual', 'unresolved', 'noCandidate')");

                            t.HasCheckConstraint("CK_CardRecord_GermanName", "(\"GermanName\" IS NOT NULL) <> (\"GermanNameUnavailableReason\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("ArchiveDex.Server.Infrastructure.Persistence.CardSpecimen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CardRecordId")
                        .HasColumnType("uuid");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("ConditionAppliedToValuation")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ImageAssetId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("MarketDataAsOf")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("ValuationAmountMinor")
                        .HasColumnType("bigint");

                    b.Property<string>("ValuationConfidence")
                        .HasColumnType("text");

                    b.Property<string>("ValuationCurrency")
                        .HasColumnType("text");

                    b.Property<string>("ValuationMethod")
                        .HasColumnType("text");

                    b.Property<string>("ValuationProvider")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ValuationReviewPendingAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ValuationSourceUrlsJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("ValuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CardRecordId");

                    b.HasIndex("ImageAssetId")
                        .IsUnique();

                    b.HasIndex("OwnerId", "CardRecordId", "Id");

                    b.ToTable("CardSpecimens", t =>
                        {
                            t.HasCheckConstraint("CK_CardSpecimen_Condition", "\"Condition\" IN ('NM', 'LP', 'MP', 'HP', 'DMG')");

                            t.HasCheckConstraint("CK_CardSpecimen_Valuation", "\"ValuationAmountMinor\" IS NULL OR (\"ValuationAmountMinor\" >= 0 AND \"ValuationCurrency\" = 'EUR' AND \"ValuedAt\" IS NOT NULL AND \"MarketDataAsOf\" IS NOT NULL AND \"ValuationProvider\" IS NOT NULL AND \"ValuationMethod\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("ArchiveDex.Server.Infrastructure.Persistence.CardmarketImport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RecordCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SourceCreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Kind", "ImportedAt");

                    b.ToTable("CardmarketImports", t =>
                        {
                            t.HasCheckConstraint("CK_CardmarketImport_Kind", "\"Kind\" IN ('products', 'prices')");
                        });
                });

            modelBuilder.Entity("ArchiveDex.Server.Infrastructure.Persistence.CardmarketPrice", b =>
                {
                    b.Property<int>("IdProduct")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Avg")
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal?>("Avg30")
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal?>("Avg30Holo")
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal?>("Avg7")
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal?>("Avg7Holo")
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal?>("Low")
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal?>("Trend")
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal?>("TrendHolo")
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("IdProduct");

                    b.ToTable("CardmarketPrices");
                });

            modelBuilder.Entity("ArchiveDex.Server.Infrastructure.Persistence.CardmarketProduct", b =>
                {
                    b.Property<int>("IdProduct")
                        .HasColumnType("integer");

                    b.Property<int>("IdCategory")
                        .HasColumnType("integer");

                    b.Property<int>("IdExpansion")
                        .HasColumnType("integer");

                    b.Property<int>("IdMetacard")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdProduct");

                    b.HasIndex("IdExpansion", "IdMetacard");

                    b.HasIndex("IdExpansion", "Name");

                    b.ToTable("CardmarketProducts");
                });

            modelBuilder.Entity("ArchiveDex.Server.Infrastructure.Persistence.CatalogCardReference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CatalogSetReferenceId")
                        .HasColumnType("uuid");

                    b.Property<string>("CatalogVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CollectorNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CrossLanguageId")
                        .HasColumnType("text");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Namespace")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumberNormalized")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrintedName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrintedNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SetTotal")
                        .HasColumnType("text");

                    b.Property<string>("VariantKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CatalogSetReferenceId");

                    b.HasIndex("Namespace", "ExternalId", "CatalogVersion", "LanguageCode", "VariantKey")
                        .IsUnique();

                    b.ToTable("CatalogCardReferences");
                });

            modelBuilder.Entity("ArchiveDex.Server.Infrastructure.Persistence.CatalogSetReference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CatalogVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Namespace")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SetIdentifier")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Namespace", "ExternalId", "CatalogVersion", "LanguageCode")
                        .IsUnique();

                    b.ToTable("CatalogSetReferences");
                });

            modelBuilder.Entity("ArchiveDex.Server.Infrastructure.Persistence.FinalizationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BatchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CaptureId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CardRecordId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SpecimenId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("CardRecordId");

                    b.HasIndex("SpecimenId");

                    b.HasIndex("OwnerId", "BatchId");

                    b.HasIndex("OwnerId", "CaptureId")
                        .IsUnique();

                    b.HasIndex("OwnerId", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("FinalizationRecords");
                });

            modelBuilder.Entity("ArchiveDex.Server.Infrastructure.Persistence.ImageAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("ByteLength")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float?>("CropConfidence")
                        .HasColumnType("real");

                    b.Property<byte[]>("CroppedContent")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("CroppedSha256")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("CroppedThumbnail")
                        .HasColumnType("bytea");

                    b.Property<Guid?>("DuplicateMatchImageId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DuplicateOverrideAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<byte[]>("NormalizedSha256")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("Thumbnail")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("UploadSha256")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DuplicateMatchImageId");

                    b.HasIndex("OwnerId", "NormalizedSha256")
                        .HasFilter("\"State\" = 'attached'");

                    b.HasIndex("OwnerId", "UploadSha256")
                        .HasFilter("\"State\" = 'attached'");

                    b.ToTable("ImageAssets", t =>
                        {
                            t.HasCheckConstraint("CK_ImageAsset_Crop", "(\"CroppedContent\" IS NULL AND \"CroppedThumbnail\" IS NULL AND \"CroppedSha256\" IS NULL) OR (\"CroppedContent\" IS NOT NULL AND \"CroppedThumbnail\" IS NOT NULL AND octet_length(\"CroppedSha256\") = 32)");

                            t.HasCheckConstraint("CK_ImageAsset_Dimensions", "\"Width\" > 0 AND \"Height\" > 0 AND \"Width\"::bigint * \"Height\" <= 30000000");

                            t.HasCheckConstraint("CK_ImageAsset_Expiry", "(\"State\" = 'draft' AND \"ExpiresAt\" IS NOT NULL) OR (\"State\" = 'attached' AND \"ExpiresAt\" IS NULL)");

                            t.HasCheckConstraint("CK_ImageAsset_NormalizedSha256", "octet_length(\"NormalizedSha256\") = 32");

                            t.HasCheckConstraint("CK_ImageAsset_State", "\"State\" IN ('draft', 'attached')");

                            t.HasCheckConstraint("CK_ImageAsset_UploadSha256", "octet_length(\"UploadSha256\") = 32");
                        });
                });

            modelBuilder.Entity("ArchiveDex.Server.Infrastructure.Persistence.SetEdition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("CardmarketExpansionId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CatalogSetReferenceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("SetIdentifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SetIdentifierNormalized")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CatalogSetReferenceId");

                    b.HasIndex("OwnerId", "SetIdentifierNormalized", "LanguageCode")
                        .IsUnique();

                    b.ToTable("SetEditions");
                });

            modelBuilder.Entity("ArchiveDex.Server.Infrastructure.Persistence.SpecimenValuationHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("AmountMinor")
                        .HasColumnType("bigint");

                    b.Property<Guid>("CardSpecimenId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("ConditionApplied")
                        .HasColumnType("boolean");

                    b.Property<string>("Confidence")
                        .HasColumnType("text");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HoldReason")
                        .HasColumnType("text");

                    b.Property<DateTime>("MarketDataAsOf")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<long?>("PreviousAmountMinor")
                        .HasColumnType("bigint");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceUrlsJson")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("ValuationRefreshJobId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ValuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CardSpecimenId");

                    b.HasIndex("ValuationRefreshJobId");

                    b.HasIndex("OwnerId", "CardSpecimenId", "RecordedAt");

                    b.ToTable("SpecimenValuationHistories", t =>
                        {
                            t.HasCheckConstraint("CK_SpecimenValuationHistory_Amount", "\"AmountMinor\" >= 0 AND \"Currency\" = 'EUR'");

                            t.HasCheckConstraint("CK_SpecimenValuationHistory_Outcome", "\"Outcome\" IN ('accepted', 'heldForReview', 'rejected')");
                        });
                });

            modelBuilder.Entity("ArchiveDex.Server.Infrastructure.Persistence.ValuationRefreshJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CardCreatedBefore")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FailedCards")
                        .HasColumnType("integer");

                    b.Property<int>("HeldCards")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastCardCreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastCardRecordId")
                        .HasColumnType("uuid");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("ProcessedCards")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalCards")
                        .HasColumnType("integer");

                    b.Property<int>("UnavailableCards")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UpdatedCards")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId")
                        .IsUnique()
                        .HasFilter("\"Status\" IN ('pending', 'running')");

                    b.HasIndex("OwnerId", "CreatedAt");

                    b.ToTable("ValuationRefreshJobs", t =>
                        {
                            t.HasCheckConstraint("CK_ValuationRefreshJob_Counts", "\"TotalCards\" >= 0 AND \"ProcessedCards\" >= 0 AND \"UpdatedCards\" >= 0 AND \"UnavailableCards\" >= 0 AND \"FailedCards\" >= 0 AND \"HeldCards\" >= 0");

                            t.HasCheckConstraint("CK_ValuationRefreshJob_Status", "\"Status\" IN ('pending', 'running', 'completed', 'completedWithErrors', 'failed')");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ArchiveDex.Server.Infrastructure.Persistence.CaptureBatch", b =>
                {
                    b.HasOne("ArchiveDex.Server.Infrastructure.Persistence.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ArchiveDex.Server.Infrastructure.Persistence.CaptureDraft", b =>
                {
                    b.HasOne("ArchiveDex.Server.Infrastructure.Persistence.CaptureBatch", null)
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ArchiveDex.Server.Infrastructure.Persistence.ImageAsset", "ImageAsset")
                        .WithOne()
                        .HasForeignKey("ArchiveDex.Server.Infrastructure.Persistence.CaptureDraft", "ImageAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArchiveDex.Server.Infrastructure.Persistence.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImageAsset");
                });

            modelBuilder.Entity("ArchiveDex.Server.Infrastructure.Persistence.CardRecord", b =>
                {
                    b.HasOne("ArchiveDex.Server.Infrastructure.Persistence.CatalogCardReference", null)
                        .WithMany()
                        .HasForeignKey("CatalogCardReferenceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ArchiveDex.Server.Infrastructure.Persistence.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArchiveDex.Server.Infrastructure.Persistence.SetEdition", "SetEdition")
                        .WithMany("CardRecords")
                        .HasForeignKey("SetEditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SetEdition");
                });

            modelBuilder.Entity("ArchiveDex.Server.Infrastructure.Persistence.CardSpecimen", b =>
                {
                    b.HasOne("ArchiveDex.Server.Infrastructure.Persistence.CardRecord", "CardRecord")
                        .WithMany("Specimens")
                        .HasForeignKey("CardRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArchiveDex.Server.Infrastructure.Persistence.ImageAsset", "ImageAsset")
                        .WithOne()
                        .HasForeignKey("ArchiveDex.Server.Infrastructure.Persistence.CardSpecimen", "ImageAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArchiveDex.Server.Infrastructure.Persistence.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CardRecord");

                    b.Navigation("ImageAsset");
                });

            modelBuilder.Entity("ArchiveDex.Server.Infrastructure.Persistence.CatalogCardReference", b =>
                {
                    b.HasOne("ArchiveDex.Server.Infrastructure.Persistence.CatalogSetReference", "CatalogSetReference")
                        .WithMany()
                        .HasForeignKey("CatalogSetReferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CatalogSetReference");
                });

            modelBuilder.Entity("ArchiveDex.Server.Infrastructure.Persistence.FinalizationRecord", b =>
                {
                    b.HasOne("ArchiveDex.Server.Infrastructure.Persistence.CaptureBatch", null)
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ArchiveDex.Server.Infrastructure.Persistence.CardRecord", null)
                        .WithMany()
                        .HasForeignKey("CardRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArchiveDex.Server.Infrastructure.Persistence.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArchiveDex.Server.Infrastructure.Persistence.CardSpecimen", null)
                        .WithMany()
                        .HasForeignKey("SpecimenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ArchiveDex.Server.Infrastructure.Persistence.ImageAsset", b =>
                {
                    b.HasOne("ArchiveDex.Server.Infrastructure.Persistence.ImageAsset", null)
                        .WithMany()
                        .HasForeignKey("DuplicateMatchImageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ArchiveDex.Server.Infrastructure.Persistence.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ArchiveDex.Server.Infrastructure.Persistence.SetEdition", b =>
                {
                    b.HasOne("ArchiveDex.Server.Infrastructure.Persistence.CatalogSetReference", "CatalogSetReference")
                        .WithMany()
                        .HasForeignKey("CatalogSetReferenceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ArchiveDex.Server.Infrastructure.Persistence.ApplicationUser", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CatalogSetReference");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("ArchiveDex.Server.Infrastructure.Persistence.SpecimenValuationHistory", b =>
                {
                    b.HasOne("ArchiveDex.Server.Infrastructure.Persistence.CardSpecimen", "CardSpecimen")
                        .WithMany("ValuationHistory")
                        .HasForeignKey("CardSpecimenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArchiveDex.Server.Infrastructure.Persistence.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArchiveDex.Server.Infrastructure.Persistence.ValuationRefreshJob", null)
                        .WithMany()
                        .HasForeignKey("ValuationRefreshJobId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CardSpecimen");
                });

            modelBuilder.Entity("ArchiveDex.Server.Infrastructure.Persistence.ValuationRefreshJob", b =>
                {
                    b.HasOne("ArchiveDex.Server.Infrastructure.Persistence.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("ArchiveDex.Server.Infrastructure.Persistence.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("ArchiveDex.Server.Infrastructure.Persistence.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArchiveDex.Server.Infrastructure.Persistence.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("ArchiveDex.Server.Infrastructure.Persistence.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ArchiveDex.Server.Infrastructure.Persistence.CardRecord", b =>
                {
                    b.Navigation("Specimens");
                });

            modelBuilder.Entity("ArchiveDex.Server.Infrastructure.Persistence.CardSpecimen", b =>
                {
                    b.Navigation("ValuationHistory");
                });

            modelBuilder.Entity("ArchiveDex.Server.Infrastructure.Persistence.SetEdition", b =>
                {
                    b.Navigation("CardRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
